### PR TITLE
Fix errors and warnings for 32-bit x86 architectures

### LINKED ISSUE #10: No support for 32-bit avx2 causes errors on i686 architectures
# Problem
We use the `avx2` module on 32 and 64 bit systems here:
https://github.com/fortanix/b64-ct/blob/bd37b722c567583280c4cefda261fd90fa66cafa/src/lib.rs#L66

But there is no support for `avx2` on 32-bit i686 since the import here is 64-bit specific:
https://github.com/fortanix/b64-ct/blob/bd37b722c567583280c4cefda261fd90fa66cafa/src/avx2.rs#L7

This causes compilation to fail for i686 targets, for example `cargo build --target=i686-unknown-linux-gnu`

# Fix
Either support a 32-bit variant or turn off on 32-bit systems

### PR DESCRIPTION
**Pull request by tvsfx**
Fixes #10 (Disable compilation of avx2 code on i686 architectures)
Also fixes `impl_lcm_array` macro to avoid warnings
Bumps patch version so we can re-release

### CODE REVIEW

**Comment by tvsfx** [comment]
[b9cbc67](https://github.com/fortanix/b64-ct/pull/11/commits/b9cbc6708103c11d92480e7b46a11922146aeb7c) updates the ubuntu image used by travis-ci, so that ci builds pass (a more up-to-date version of glibc was required for the wasm tests)

**Comment by jethrogb** [comment]
Can't you fix the `avx2` module so it works on 32-bit?

File: src/encode/mod.rs [hunk 1]
```diff
@@ -59,16 +59,16 @@ trait SplitArrayExt {
...
 
-        impl_lcm_array!(@split $($am / )* $a, $lcm);
-        impl_lcm_array!(@split $($bm / )* $b, $lcm);
+        impl_lcm_array!(@split $($am / )? $a, $lcm);
+        impl_lcm_array!(@split $($bm / )? $b, $lcm);
     };
-    (@split $($nm:ident / )* $n:literal, $lcm:literal) => {
-        $(#[cfg(all(not($nm), $nm))])*
+    (@split $nm:ident / $n:literal, $lcm:literal) => {};
+    (@split $n:literal, $lcm:literal) => {
```
Comment (jethrogb) [inline src/encode/mod.rs]: This change seems unrelated?

Comment (tvsfx) [reply src/encode/mod.rs]: You're right, it should probably have been its own PR. I squeezed it in here since this macro produced warnings on all architectures, and I was in the process of fixing all warnings/errors on i686

File: src/decode/mod.rs [hunk 2]
```diff
@@ -367,7 +367,7 @@ mod tests {
 
         let mut v: Vec<u8> = vec![];
         let bytes_per_line = BASE64_PEM_WRAP * 3 / 4;
-        for _i in 0..2*bytes_per_line {
+        for _i in 0..2 * bytes_per_line {
```
Comment (jethrogb) [inline src/decode/mod.rs]: I actually think this is less clear since the precedence of `*` is before `..`.

Comment (tvsfx) [reply src/decode/mod.rs]: Agree, but it's what `cargo fmt` prefers. I'll put some brackets to clarify precedence.

**Comment by tvsfx** [comment]
> Can't you fix the `avx2` module so it works on 32-bit?

I've done this now, and added a 32-bit check in CI.
Just need to find the right way to run 32-bit tests on `amd64` to complete the PR (what I tried now failed in CI)

**Comment by jethrogb** [comment]
LGTM but can you squash all your commits?

**Review by jethrogb — APPROVED** [review]

**Comment by tvsfx** [comment]
bors ping
